<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice rule</name>
  <uuid>c5a6ad88-84a1-4e3b-b62b-b86256e572b9</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Name is defined
then
    set decision to "Hello " + Name + "! " + 'Weather advice';]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
